FROM python:3.10-slim-buster

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update \
  && apt-get install -y build-essential \
  && apt-get install -y libpq-dev \
  && apt-get purge -y --auto-remove -o APT::AutoRemove::ReccomendsImportant=false \
  && rm -rf /var/lib/apt/lists/*


RUN pip3 install --upgrade pip

COPY ./requirements.txt . 
RUN pip install -r requirements.txt

COPY ./docker/local/django/entrypoint /entrypoint 
RUN sed -i 's/\r$//g' /entrypoint
RUN chmod +x /entrypoint

COPY ./docker/local/django/start /start
RUN sed -i 's/\r$//g' /start
RUN chmod +x /start

COPY ./docker/local/django/celery/worker/start /start-celeryworker
RUN sed -i 's/\r$//g' /start-celeryworker
RUN chmod +x /start-celeryworker

COPY ./docker/local/django/celery/beat/start /start-celerybeat 
RUN sed -i 's/\r$//g' /start-celerybeat 
RUN chmod +x /start-celerybeat 

COPY ./docker/local/django/celery/flower/start /start-flower 
RUN sed -i 's/\r$//g' /start-flower 
RUN chmod +x /start-flower

ENTRYPOINT [ "/entrypoint" ]
  