version: '3.10'

services:
    web:
      build:
        context: .
        dockerfile: ./docker/local/django/dockerfile
      container_name: django-celery
      command: /start
      volumes:
        - .:/app
      ports:
        - 8080:8000 
      env_file:
        - .env
      depends_on:
        - db
        - redis

    db:
      image: postgres:14-alpine
      container_name: postgres_db
      volumes:
          - postgres_data:/var/lib/postgresql/data
      environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_DATABASE}
      ports:
          - 5432:5432

          
    redis:
        image: redis:6-alpine



    celery_worker:
        build:
           context: .
           dockerfile: ./docker/local/django/Dockerfile

        command: /start-celeryworker
        container_name: celery-worker
        volumes:
           - .:/app
        env_file: 
           - .env  
        depends_on:
           - redis
           - db  

    celery_beat:
        build:
          context: .
          dockerfile: ./docker/local/django/Dockerfile
        command: /start-celerybeat
        volumes:
            - .:/app
        env_file: 
            - .env  
        depends_on:
            - redis
            - db  
   
    celery_flower:
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        command: /start-flower
        volumes:
          - .:/app
        ports:
          - 5557:5555
        env_file:
          - .env
        depends_on:
          - db
          - redis
          - celery_worker

volumes:
     postgres_data: 
    
          

